/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class AdminView extends javax.swing.JFrame {

    private int x, y;
    private long userId;
    public AdminView(long userId) {
        initComponents();
        HospitalStore store = HospitalStore.getInstance();
        store.loadUsersFromJson();
        this.userId = userId;
        loadUsersInCombos();
        configureComponentNames();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminRootPanel = new packagee.PanelRound();
        adminHeaderPanel = new packagee.PanelRound();
        adminCloseButton = new javax.swing.JButton();
        adminTitleLabel = new javax.swing.JLabel();
        adminContentPanel = new packagee.PanelRound();
        adminOpenDoctorViewButton = new javax.swing.JButton();
        adminOpenPatientViewButton = new javax.swing.JButton();
        adminDoctorFirstnameLabel = new javax.swing.JLabel();
        adminDoctorFirstnameField = new javax.swing.JTextField();
        adminDoctorLastnameLabel = new javax.swing.JLabel();
        adminDoctorLastnameField = new javax.swing.JTextField();
        adminDoctorIdLabel = new javax.swing.JLabel();
        adminDoctorIdField = new javax.swing.JTextField();
        adminDoctorSpecialtyLabel = new javax.swing.JLabel();
        adminDoctorLicenseLabel = new javax.swing.JLabel();
        adminDoctorLicenseField = new javax.swing.JTextField();
        adminDoctorOfficeLabel = new javax.swing.JLabel();
        adminDoctorOfficeField = new javax.swing.JTextField();
        adminDoctorUsernameLabel = new javax.swing.JLabel();
        adminDoctorUsernameField = new javax.swing.JTextField();
        adminDoctorPasswordLabel = new javax.swing.JLabel();
        adminDoctorPasswordField = new javax.swing.JTextField();
        adminDoctorPasswordConfirmationLabel = new javax.swing.JLabel();
        adminDoctorPasswordConfirmationField = new javax.swing.JTextField();
        adminDoctorSpecialtyComboBox = new javax.swing.JComboBox<>();
        adminSaveDoctorButton = new javax.swing.JButton();
        adminFirstSeparator = new javax.swing.JSeparator();
        adminDoctorSelectorComboBox = new javax.swing.JComboBox<>();
        adminDoctorSelectorLabel = new javax.swing.JLabel();
        adminPatientSelectorLabel = new javax.swing.JLabel();
        adminPatientSelectorComboBox = new javax.swing.JComboBox<>();
        adminSecondSeparator = new javax.swing.JSeparator();
        adminLogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        adminRootPanel.setRadius(50);

        adminHeaderPanel.setRadius(50);
        adminHeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        adminHeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        adminCloseButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminCloseButton.setText("X");
        adminCloseButton.setBorderPainted(false);
        adminCloseButton.setContentAreaFilled(false);
        adminCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminCloseButton.setFocusable(false);
        adminCloseButton.setRequestFocusEnabled(false);
        adminCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        adminTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        adminTitleLabel.setText("ADMIN VIEW");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(adminHeaderPanel);
        adminHeaderPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adminTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminCloseButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adminCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminTitleLabel))
        );

        adminOpenDoctorViewButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        adminOpenDoctorViewButton.setText("DOCTOR VIEW");
        adminOpenDoctorViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        adminOpenPatientViewButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        adminOpenPatientViewButton.setText("PATIENT VIEW");
        adminOpenPatientViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        adminDoctorFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorFirstnameLabel.setText("Firstname");

        adminDoctorFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorLastnameLabel.setText("Lastname");

        adminDoctorLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorIdLabel.setText("ID");

        adminDoctorIdField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorSpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorSpecialtyLabel.setText("Specialty");

        adminDoctorLicenseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorLicenseLabel.setText("License Number");

        adminDoctorLicenseField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorOfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorOfficeLabel.setText("Assigned office");

        adminDoctorOfficeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorUsernameLabel.setText("User");

        adminDoctorUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorPasswordLabel.setText("Password");

        adminDoctorPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorPasswordConfirmationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorPasswordConfirmationLabel.setText("Password confirmation");

        adminDoctorPasswordConfirmationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        adminDoctorSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        adminSaveDoctorButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminSaveDoctorButton.setText("Save");
        adminSaveDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        adminFirstSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        adminDoctorSelectorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        adminDoctorSelectorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminDoctorSelectorLabel.setText("Doctor");

        adminPatientSelectorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminPatientSelectorLabel.setText("Patient");

        adminPatientSelectorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminPatientSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        adminSecondSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        adminLogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminLogoutButton.setText("Logout");
        adminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(adminContentPanel);
        adminContentPanel.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(adminSaveDoctorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminDoctorFirstnameLabel)
                                    .addComponent(adminDoctorSpecialtyLabel))
                                .addGap(18, 18, 18)
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(adminDoctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(adminDoctorLicenseLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(adminDoctorLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(adminDoctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(adminDoctorLastnameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(adminDoctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(adminDoctorIdLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(adminDoctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(adminDoctorOfficeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(adminDoctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(adminDoctorUsernameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(adminDoctorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(adminDoctorPasswordLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(adminDoctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(adminDoctorPasswordConfirmationLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(adminDoctorPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(333, 333, 333)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminOpenDoctorViewButton)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(adminDoctorSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(adminDoctorSelectorLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminLogoutButton)
                        .addGap(318, 318, 318)))
                .addComponent(adminFirstSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminOpenPatientViewButton)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(adminPatientSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(adminPatientSelectorLabel)))
                .addGap(88, 88, 88))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(adminSecondSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(adminFirstSeparator)
                .addContainerGap())
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDoctorFirstnameLabel)
                    .addComponent(adminDoctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDoctorLastnameLabel)
                    .addComponent(adminDoctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDoctorIdLabel)
                    .addComponent(adminDoctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDoctorSpecialtyLabel)
                    .addComponent(adminDoctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDoctorLicenseLabel)
                    .addComponent(adminDoctorLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminDoctorOfficeLabel)
                    .addComponent(adminDoctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminDoctorUsernameLabel)
                            .addComponent(adminDoctorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminDoctorPasswordLabel)
                            .addComponent(adminDoctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminDoctorPasswordConfirmationLabel)
                            .addComponent(adminDoctorPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(adminDoctorSelectorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(adminDoctorSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(adminOpenDoctorViewButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(adminSaveDoctorButton)
                .addGap(123, 123, 123)
                .addComponent(adminLogoutButton)
                .addGap(38, 38, 38))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(adminPatientSelectorLabel)
                .addGap(18, 18, 18)
                .addComponent(adminPatientSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(adminOpenPatientViewButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(adminSecondSeparator)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(adminRootPanel);
        adminRootPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(adminHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String firstname = adminDoctorFirstnameField.getText();
        String lastname = adminDoctorLastnameField.getText();
        String id = adminDoctorIdField.getText();
        String spec = adminDoctorSpecialtyComboBox.getItemAt(adminDoctorSpecialtyComboBox.getSelectedIndex());
        String licenseNumber = adminDoctorLicenseField.getText();
        String assignedOffice = adminDoctorOfficeField.getText();
        String username = adminDoctorUsernameField.getText();
        String password = adminDoctorPasswordField.getText();
        String comPassword = adminDoctorPasswordConfirmationField.getText();
        UserController controller = new UserController();
        Response response = controller.registerDoctor(id, username, firstname, lastname, password, comPassword,
                spec, licenseNumber, assignedOffice);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            loadUsersInCombos();
            adminDoctorFirstnameField.setText("");
            adminDoctorLastnameField.setText("");
            adminDoctorIdField.setText("");
            adminDoctorLicenseField.setText("");
            adminDoctorOfficeField.setText("");
            adminDoctorUsernameField.setText("");
            adminDoctorPasswordField.setText("");
            adminDoctorPasswordConfirmationField.setText("");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String idDoctor = adminDoctorSelectorComboBox.getItemAt(adminDoctorSelectorComboBox.getSelectedIndex());
        Response selectedDoctor = new CatalogController().getUser(idDoctor);
        if (!selectedDoctor.isSuccess()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un doctor valido.");
            return;
        }
        org.json.JSONObject doctorData = new org.json.JSONObject(selectedDoctor.getData());
        if (!"doctor".equals(doctorData.getString("type"))) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un doctor valido.");
            return;
        }
        DoctorView doctor = new DoctorView(userId, doctorData.getLong("id"));
        this.setVisible(false);
        doctor.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        LoginView login = new LoginView();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String idPatient = adminPatientSelectorComboBox.getItemAt(adminPatientSelectorComboBox.getSelectedIndex());
        Response selectedPatient = new CatalogController().getUser(idPatient);
        if (!selectedPatient.isSuccess()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un paciente valido.");
            return;
        }
        org.json.JSONObject patientData = new org.json.JSONObject(selectedPatient.getData());
        if (!"patient".equals(patientData.getString("type"))) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un paciente valido.");
            return;
        }
        PatientView patient = new PatientView(userId, patientData.getLong("id"));
        this.setVisible(false);
        patient.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loadUsersInCombos() {
        adminDoctorSelectorComboBox.removeAllItems();
        adminPatientSelectorComboBox.removeAllItems();
        adminDoctorSelectorComboBox.addItem("Select one");
        adminPatientSelectorComboBox.addItem("Select one");
        org.json.JSONArray doctors = new org.json.JSONArray(new CatalogController().getDoctors().getData());
        for (int i = 0; i < doctors.length(); i++) {
            adminDoctorSelectorComboBox.addItem(String.valueOf(doctors.getJSONObject(i).getLong("id")));
        }
        org.json.JSONArray patients = new org.json.JSONArray(new CatalogController().getPatients().getData());
        for (int i = 0; i < patients.length(); i++) {
            adminPatientSelectorComboBox.addItem(String.valueOf(patients.getJSONObject(i).getLong("id")));
        }
    }

    private void configureComponentNames() {
        adminCloseButton.setName("adminCloseButton");
        adminLogoutButton.setName("adminLogoutButton");
        adminOpenDoctorViewButton.setName("adminOpenDoctorViewButton");
        adminOpenPatientViewButton.setName("adminOpenPatientViewButton");
        adminSaveDoctorButton.setName("adminSaveDoctorButton");
        adminDoctorSpecialtyComboBox.setName("adminDoctorSpecialtyComboBox");
        adminDoctorSelectorComboBox.setName("adminDoctorSelectorComboBox");
        adminPatientSelectorComboBox.setName("adminPatientSelectorComboBox");
        adminDoctorFirstnameField.setName("adminDoctorFirstnameField");
        adminDoctorLastnameField.setName("adminDoctorLastnameField");
        adminDoctorIdField.setName("adminDoctorIdField");
        adminDoctorLicenseField.setName("adminDoctorLicenseField");
        adminDoctorOfficeField.setName("adminDoctorOfficeField");
        adminDoctorUsernameField.setName("adminDoctorUsernameField");
        adminDoctorPasswordField.setName("adminDoctorPasswordField");
        adminDoctorPasswordConfirmationField.setName("adminDoctorPasswordConfirmationField");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminCloseButton;
    private javax.swing.JButton adminLogoutButton;
    private javax.swing.JButton adminOpenDoctorViewButton;
    private javax.swing.JButton adminOpenPatientViewButton;
    private javax.swing.JButton adminSaveDoctorButton;
    private javax.swing.JComboBox<String> adminDoctorSpecialtyComboBox;
    private javax.swing.JComboBox<String> adminDoctorSelectorComboBox;
    private javax.swing.JComboBox<String> adminPatientSelectorComboBox;
    private javax.swing.JLabel adminTitleLabel;
    private javax.swing.JLabel adminDoctorUsernameLabel;
    private javax.swing.JLabel adminDoctorPasswordLabel;
    private javax.swing.JLabel adminDoctorPasswordConfirmationLabel;
    private javax.swing.JLabel adminDoctorSelectorLabel;
    private javax.swing.JLabel adminPatientSelectorLabel;
    private javax.swing.JLabel adminDoctorFirstnameLabel;
    private javax.swing.JLabel adminDoctorLastnameLabel;
    private javax.swing.JLabel adminDoctorIdLabel;
    private javax.swing.JLabel adminDoctorSpecialtyLabel;
    private javax.swing.JLabel adminDoctorLicenseLabel;
    private javax.swing.JLabel adminDoctorOfficeLabel;
    private javax.swing.JSeparator adminFirstSeparator;
    private javax.swing.JSeparator adminSecondSeparator;
    private javax.swing.JTextField adminDoctorPasswordConfirmationField;
    private javax.swing.JTextField adminDoctorFirstnameField;
    private javax.swing.JTextField adminDoctorLastnameField;
    private javax.swing.JTextField adminDoctorIdField;
    private javax.swing.JTextField adminDoctorLicenseField;
    private javax.swing.JTextField adminDoctorOfficeField;
    private javax.swing.JTextField adminDoctorUsernameField;
    private javax.swing.JTextField adminDoctorPasswordField;
    private packagee.PanelRound adminRootPanel;
    private packagee.PanelRound adminHeaderPanel;
    private packagee.PanelRound adminContentPanel;
    // End of variables declaration//GEN-END:variables
}
