/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame extends javax.swing.JFrame {

    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    public NewJFrame() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        HospitalStore store = HospitalStore.getInstance();
        store.loadUsersFromJson();
        this.users = store.getUsers();
        this.appointments = store.getAppointments();
        this.hospitalizations = store.getHospitalizations();
        configureComponentNames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginRootPanel = new packagee.PanelRound();
        loginHeaderPanel = new packagee.PanelRound();
        loginCloseButton = new javax.swing.JButton();
        loginTabbedPane = new javax.swing.JTabbedPane();
        loginFormPanel = new packagee.PanelRound();
        loginTitleLabel = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JTextField();
        loginPasswordLabel = new javax.swing.JLabel();
        loginSubmitButton = new javax.swing.JButton();
        registerPatientPanel = new javax.swing.JPanel();
        registerPatientFirstnameLabel = new javax.swing.JLabel();
        registerPatientFirstnameField = new javax.swing.JTextField();
        registerPatientLastnameLabel = new javax.swing.JLabel();
        registerPatientLastnameField = new javax.swing.JTextField();
        registerPatientIdLabel = new javax.swing.JLabel();
        registerPatientIdField = new javax.swing.JTextField();
        registerPatientGenderLabel = new javax.swing.JLabel();
        registerPatientPhoneLabel = new javax.swing.JLabel();
        registerPatientPhoneField = new javax.swing.JTextField();
        registerPatientEmailLabel = new javax.swing.JLabel();
        registerPatientEmailField = new javax.swing.JTextField();
        registerPatientUsernameLabel = new javax.swing.JLabel();
        registerPatientUsernameField = new javax.swing.JTextField();
        registerPatientPasswordField = new javax.swing.JTextField();
        registerPatientPasswordLabel = new javax.swing.JLabel();
        registerPatientPasswordConfirmationLabel = new javax.swing.JLabel();
        registerPatientPasswordConfirmationField = new javax.swing.JTextField();
        registerPatientGenderComboBox = new javax.swing.JComboBox<>();
        registerPatientButton = new javax.swing.JButton();
        registerPatientAddressLabel = new javax.swing.JLabel();
        registerPatientAddressField = new javax.swing.JTextField();
        registerPatientBirthdateLabel = new javax.swing.JLabel();
        registerPatientBirthdateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        loginRootPanel.setRadius(50);

        loginHeaderPanel.setRadius(50);
        loginHeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        loginHeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        loginCloseButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginCloseButton.setText("X");
        loginCloseButton.setBorderPainted(false);
        loginCloseButton.setContentAreaFilled(false);
        loginCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginCloseButton.setFocusable(false);
        loginCloseButton.setRequestFocusEnabled(false);
        loginCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(loginHeaderPanel);
        loginHeaderPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginCloseButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginCloseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        loginTitleLabel.setText("LOGIN");

        loginUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameLabel.setText("USERNAME");

        loginPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordLabel.setText("PASSWORD");

        loginSubmitButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginSubmitButton.setText("ENTER");
        loginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(loginFormPanel);
        loginFormPanel.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(loginTitleLabel)
                .addGap(481, 481, 481))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(loginSubmitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(loginTitleLabel)
                .addGap(74, 74, 74)
                .addComponent(loginUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(loginSubmitButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        loginTabbedPane.addTab("Login", loginFormPanel);

        registerPatientFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientFirstnameLabel.setText("Firstname");

        registerPatientFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientLastnameLabel.setText("Lastname");

        registerPatientLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientIdLabel.setText("ID");

        registerPatientIdField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientGenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientGenderLabel.setText("Gender");

        registerPatientPhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientPhoneLabel.setText("Phone");

        registerPatientPhoneField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientEmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientEmailLabel.setText("Email");

        registerPatientEmailField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientUsernameLabel.setText("User");

        registerPatientUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientPasswordLabel.setText("Password");

        registerPatientPasswordConfirmationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientPasswordConfirmationLabel.setText("Password confirmation");

        registerPatientPasswordConfirmationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientPasswordConfirmationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        registerPatientGenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        registerPatientButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientButton.setText("Save");
        registerPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        registerPatientAddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientAddressLabel.setText("Address");

        registerPatientAddressField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientBirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientBirthdateLabel.setText("Birthdate");

        registerPatientBirthdateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(registerPatientPanel);
        registerPatientPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(registerPatientPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerPatientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerPatientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(registerPatientUsernameLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(registerPatientPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(registerPatientButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(registerPatientPasswordConfirmationLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerPatientBirthdateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerPatientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerPatientFirstnameLabel)
                                .addGap(34, 34, 34)
                                .addComponent(registerPatientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerPatientLastnameLabel)
                            .addComponent(registerPatientAddressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerPatientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerPatientIdLabel)
                                .addGap(30, 30, 30)
                                .addComponent(registerPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerPatientGenderLabel)
                                .addGap(26, 26, 26)
                                .addComponent(registerPatientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerPatientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerPatientPhoneLabel)
                                .addGap(18, 18, 18)
                                .addComponent(registerPatientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerPatientEmailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(registerPatientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPatientFirstnameLabel)
                    .addComponent(registerPatientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPatientLastnameLabel)
                    .addComponent(registerPatientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPatientIdLabel)
                    .addComponent(registerPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPatientGenderLabel)
                    .addComponent(registerPatientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerPatientBirthdateLabel)
                        .addComponent(registerPatientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registerPatientAddressLabel)
                        .addComponent(registerPatientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registerPatientPhoneLabel)
                        .addComponent(registerPatientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerPatientEmailLabel)
                        .addComponent(registerPatientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(registerPatientUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPatientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerPatientPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPatientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerPatientPasswordConfirmationLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPatientPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(registerPatientButton)
                .addGap(42, 42, 42))
        );

        loginTabbedPane.addTab("Patient register", registerPatientPanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(loginRootPanel);
        loginRootPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(loginTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(loginHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UserController controller = new UserController();
        Response response = controller.login(loginUsernameField.getText(), loginPasswordField.getText());
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (!response.isSuccess()) {
            return;
        }
        User selectedUser = HospitalStore.getInstance().findUserByUsername(loginUsernameField.getText());
        if (selectedUser instanceof Administrator ) {
            NewJFrame11 admin = new NewJFrame11(selectedUser.getId());
            this.setVisible(false);
            admin.setVisible(true);
        } else if (selectedUser instanceof Doctor ) {
            NewJFrame111 doctor = new NewJFrame111(selectedUser.getId(), selectedUser.getId());
            this.setVisible(false);
            doctor.setVisible(true);
        } else {
            NewJFrame1 patient = new NewJFrame1(selectedUser.getId(), selectedUser.getId());
            this.setVisible(false);
            patient.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String firstname = registerPatientFirstnameField.getText();
        String lastname = registerPatientLastnameField.getText();
        String id = registerPatientIdField.getText();
        boolean gender = registerPatientGenderComboBox.getSelectedIndex() == 1;
        String birth = registerPatientBirthdateField.getText();
        String address = registerPatientAddressField.getText();
        String phone = registerPatientPhoneField.getText();
        String email = registerPatientEmailField.getText();
        String user = registerPatientUsernameField.getText();
        String password = registerPatientPasswordField.getText();
        String comPassword = registerPatientPasswordConfirmationField.getText();
        UserController controller = new UserController();
        Response response = controller.registerPatient(id, user, firstname, lastname, password, comPassword,
                email, birth, gender, phone, address);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            registerPatientFirstnameField.setText("");
            registerPatientLastnameField.setText("");
            registerPatientIdField.setText("");
            registerPatientPhoneField.setText("");
            registerPatientEmailField.setText("");
            registerPatientUsernameField.setText("");
            registerPatientPasswordField.setText("");
            registerPatientPasswordConfirmationField.setText("");
            registerPatientAddressField.setText("");
            registerPatientBirthdateField.setText("");
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void configureComponentNames() {
        loginCloseButton.setName("loginCloseButton");
        loginSubmitButton.setName("loginSubmitButton");
        registerPatientButton.setName("patientRegisterButton");
        registerPatientGenderComboBox.setName("patientRegisterGenderComboBox");
        loginUsernameField.setName("loginUsernameField");
        loginPasswordField.setName("loginPasswordField");
        registerPatientFirstnameField.setName("patientRegisterFirstnameField");
        registerPatientLastnameField.setName("patientRegisterLastnameField");
        registerPatientIdField.setName("patientRegisterIdField");
        registerPatientPhoneField.setName("patientRegisterPhoneField");
        registerPatientEmailField.setName("patientRegisterEmailField");
        registerPatientUsernameField.setName("patientRegisterUsernameField");
        registerPatientPasswordField.setName("patientRegisterPasswordField");
        registerPatientPasswordConfirmationField.setName("patientRegisterPasswordConfirmationField");
        registerPatientAddressField.setName("patientRegisterAddressField");
        registerPatientBirthdateField.setName("patientRegisterBirthdateField");
        loginTabbedPane.setName("loginAndRegistrationTabs");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginCloseButton;
    private javax.swing.JButton loginSubmitButton;
    private javax.swing.JButton registerPatientButton;
    private javax.swing.JComboBox<String> registerPatientGenderComboBox;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JLabel registerPatientUsernameLabel;
    private javax.swing.JLabel registerPatientPasswordLabel;
    private javax.swing.JLabel registerPatientPasswordConfirmationLabel;
    private javax.swing.JLabel registerPatientAddressLabel;
    private javax.swing.JLabel registerPatientBirthdateLabel;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JLabel registerPatientFirstnameLabel;
    private javax.swing.JLabel registerPatientLastnameLabel;
    private javax.swing.JLabel registerPatientIdLabel;
    private javax.swing.JLabel registerPatientGenderLabel;
    private javax.swing.JLabel registerPatientPhoneLabel;
    private javax.swing.JLabel registerPatientEmailLabel;
    private javax.swing.JPanel registerPatientPanel;
    private javax.swing.JTabbedPane loginTabbedPane;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JTextField registerPatientPasswordConfirmationField;
    private javax.swing.JTextField registerPatientAddressField;
    private javax.swing.JTextField registerPatientBirthdateField;
    private javax.swing.JTextField loginPasswordField;
    private javax.swing.JTextField registerPatientFirstnameField;
    private javax.swing.JTextField registerPatientLastnameField;
    private javax.swing.JTextField registerPatientIdField;
    private javax.swing.JTextField registerPatientPhoneField;
    private javax.swing.JTextField registerPatientEmailField;
    private javax.swing.JTextField registerPatientUsernameField;
    private javax.swing.JTextField registerPatientPasswordField;
    private packagee.PanelRound loginRootPanel;
    private packagee.PanelRound loginHeaderPanel;
    private packagee.PanelRound loginFormPanel;
    // End of variables declaration//GEN-END:variables
}
