/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class PatientView extends javax.swing.JFrame implements StoreObserver {

    private int x, y;
    private long userId;
    private long patientId;

    public PatientView(long userId, long patientId) {
        initComponents();
        HospitalStore store = HospitalStore.getInstance();
        store.loadUsersFromJson();
        this.userId = userId;
        this.patientId = patientId;
        JSONObject userData = new JSONObject(new CatalogController().getUser(String.valueOf(userId)).getData());
        if ("admin".equals(userData.getString("type"))) {
            patientBackButton.setVisible(true);
        } else {
            patientBackButton.setVisible(false);
        }
        loadPatientData();
        loadRequestCombos();
        refreshAppointmentsTable();
        configureComponentNames();
        store.addObserver(this);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientRootPanel = new packagee.PanelRound();
        patientHeaderPanel = new packagee.PanelRound();
        patientCloseButton = new javax.swing.JButton();
        patientTitleLabel = new javax.swing.JLabel();
        patientBackButton = new javax.swing.JButton();
        patientTabbedPane = new javax.swing.JTabbedPane();
        patientHistoryPanel = new javax.swing.JPanel();
        patientAppointmentsScrollPane = new javax.swing.JScrollPane();
        patientAppointmentsTable = new javax.swing.JTable();
        patientRefreshAppointmentsButton = new javax.swing.JButton();
        patientLogoutButton = new javax.swing.JButton();
        patientProfilePanel = new javax.swing.JPanel();
        patientFirstnameLabel = new javax.swing.JLabel();
        patientFirstnameField = new javax.swing.JTextField();
        patientLastnameLabel = new javax.swing.JLabel();
        patientLastnameField = new javax.swing.JTextField();
        patientBirthdateLabel = new javax.swing.JLabel();
        patientBirthdateField = new javax.swing.JTextField();
        patientGenderLabel = new javax.swing.JLabel();
        patientEmailLabel = new javax.swing.JLabel();
        patientEmailField = new javax.swing.JTextField();
        patientPhoneLabel = new javax.swing.JLabel();
        patientPhoneField = new javax.swing.JTextField();
        patientAddressLabel = new javax.swing.JLabel();
        patientAddressField = new javax.swing.JTextField();
        patientPasswordField = new javax.swing.JTextField();
        patientPasswordLabel = new javax.swing.JLabel();
        patientPasswordConfirmationLabel = new javax.swing.JLabel();
        patientPasswordConfirmationField = new javax.swing.JTextField();
        patientSaveProfileButton = new javax.swing.JButton();
        patientUsernameLabel = new javax.swing.JLabel();
        patientUsernameField = new javax.swing.JTextField();
        patientGenderComboBox = new javax.swing.JComboBox<>();
        patientRequestsPanel = new javax.swing.JPanel();
        patientAppointmentModeLabel = new javax.swing.JLabel();
        patientBySpecialtyRadioButton = new javax.swing.JRadioButton();
        patientByDoctorRadioButton = new javax.swing.JRadioButton();
        patientFirstSeparator = new javax.swing.JSeparator();
        patientAppointmentDateLabel = new javax.swing.JLabel();
        patientAppointmentDateField = new javax.swing.JTextField();
        patientAppointmentTimeField = new javax.swing.JTextField();
        patientAppointmentTimeLabel = new javax.swing.JLabel();
        patientAppointmentTypeLabel = new javax.swing.JLabel();
        patientAppointmentReasonLabel = new javax.swing.JLabel();
        patientAppointmentTypeComboBox = new javax.swing.JComboBox<>();
        patientRequestAppointmentButton = new javax.swing.JButton();
        patientSecondSeparator = new javax.swing.JSeparator();
        patientHospitalizationTitleLabel = new javax.swing.JLabel();
        patientHospitalizationReasonLabel = new javax.swing.JLabel();
        patientHospitalizationDoctorLabel = new javax.swing.JLabel();
        patientHospitalizationDoctorComboBox = new javax.swing.JComboBox<>();
        patientHospitalizationDateField = new javax.swing.JTextField();
        patientHospitalizationDateLabel = new javax.swing.JLabel();
        patientRoomTypeLabel = new javax.swing.JLabel();
        patientRoomTypeComboBox = new javax.swing.JComboBox<>();
        patientHospitalizationObservationsLabel = new javax.swing.JLabel();
        patientHospitalizationObservationsScrollPane = new javax.swing.JScrollPane();
        patientHospitalizationObservationsArea = new javax.swing.JTextArea();
        patientRequestHospitalizationButton = new javax.swing.JButton();
        patientCancelTitleLabel = new javax.swing.JLabel();
        patientCancelAppointmentLabel = new javax.swing.JLabel();
        patientCancelReasonLabel = new javax.swing.JLabel();
        patientCancelReasonScrollPane = new javax.swing.JScrollPane();
        patientCancelReasonArea = new javax.swing.JTextArea();
        patientCancelAppointmentButton = new javax.swing.JButton();
        patientHospitalizationReasonScrollPane = new javax.swing.JScrollPane();
        patientHospitalizationReasonArea = new javax.swing.JTextArea();
        patientAppointmentReasonScrollPane = new javax.swing.JScrollPane();
        patientAppointmentReasonArea = new javax.swing.JTextArea();
        patientCancelAppointmentComboBox = new javax.swing.JComboBox<>();
        patientDoctorOrSpecialtyComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        patientRootPanel.setRadius(50);

        patientHeaderPanel.setRadius(50);
        patientHeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        patientHeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        patientCloseButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCloseButton.setText("X");
        patientCloseButton.setBorderPainted(false);
        patientCloseButton.setContentAreaFilled(false);
        patientCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        patientCloseButton.setFocusable(false);
        patientCloseButton.setRequestFocusEnabled(false);
        patientCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        patientTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        patientTitleLabel.setText("PATIENT VIEW");

        patientBackButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientBackButton.setText("Back");
        patientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(patientHeaderPanel);
        patientHeaderPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(patientTitleLabel)
                .addGap(29, 29, 29)
                .addComponent(patientBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientCloseButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(patientCloseButton))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientBackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(patientTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        patientAppointmentsTable.setAutoCreateRowSorter(true);
        patientAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientAppointmentsScrollPane.setViewportView(patientAppointmentsTable);

        patientRefreshAppointmentsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRefreshAppointmentsButton.setText("Refresh");
        patientRefreshAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        patientLogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientLogoutButton.setText("Logout");
        patientLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(patientHistoryPanel);
        patientHistoryPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(patientAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(patientRefreshAppointmentsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientLogoutButton)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(patientAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientRefreshAppointmentsButton)
                    .addComponent(patientLogoutButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        patientTabbedPane.addTab("Appointment history", patientHistoryPanel);

        patientFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientFirstnameLabel.setText("Firstname");

        patientFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientLastnameLabel.setText("Lastname");

        patientLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientBirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientBirthdateLabel.setText("Birthdate");

        patientBirthdateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientGenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientGenderLabel.setText("Gender");

        patientEmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientEmailLabel.setText("Email");

        patientEmailField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientPhoneLabel.setText("Phone");

        patientPhoneField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientAddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAddressLabel.setText("Address");

        patientAddressField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientPasswordLabel.setText("Password");

        patientPasswordConfirmationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientPasswordConfirmationLabel.setText("Password confirmation");

        patientPasswordConfirmationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientSaveProfileButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientSaveProfileButton.setText("Save");
        patientSaveProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        patientUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientUsernameLabel.setText("User");

        patientUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientGenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(patientProfilePanel);
        patientProfilePanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(patientFirstnameLabel)
                .addGap(18, 18, 18)
                .addComponent(patientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(patientLastnameLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientPhoneLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientAddressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientBirthdateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientGenderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(patientEmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(patientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(patientSaveProfileButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(patientPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(patientPasswordConfirmationLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(patientPasswordLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(patientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(patientUsernameLabel)))
                            .addComponent(patientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientFirstnameLabel)
                    .addComponent(patientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientLastnameLabel)
                    .addComponent(patientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientBirthdateLabel)
                    .addComponent(patientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderLabel)
                    .addComponent(patientEmailLabel)
                    .addComponent(patientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPhoneLabel)
                    .addComponent(patientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientAddressLabel)
                    .addComponent(patientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(patientUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(patientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordConfirmationLabel)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(patientSaveProfileButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        patientTabbedPane.addTab("Modify info", patientProfilePanel);

        patientAppointmentModeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAppointmentModeLabel.setText("Request medical appointment");

        patientBySpecialtyRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientBySpecialtyRadioButton.setText("Specialty");
        patientBySpecialtyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        patientByDoctorRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientByDoctorRadioButton.setText("Doctor");
        patientByDoctorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        patientFirstSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        patientAppointmentDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAppointmentDateLabel.setText("Appointment date");

        patientAppointmentDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientAppointmentTimeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientAppointmentTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAppointmentTimeLabel.setText("Appointment time");

        patientAppointmentTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAppointmentTypeLabel.setText("Appointment type");

        patientAppointmentReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAppointmentReasonLabel.setText("Appointment reason");

        patientAppointmentTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAppointmentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        patientRequestAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRequestAppointmentButton.setText("Create");
        patientRequestAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        patientSecondSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        patientHospitalizationTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientHospitalizationTitleLabel.setText("Request hospitalization");

        patientHospitalizationReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientHospitalizationReasonLabel.setText("Hospitalization reason");

        patientHospitalizationDoctorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientHospitalizationDoctorLabel.setText("Attending doctor");

        patientHospitalizationDoctorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationDoctorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        patientHospitalizationDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientHospitalizationDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientHospitalizationDateLabel.setText("Estimated date of admission");
        patientHospitalizationDateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        patientRoomTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRoomTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientRoomTypeLabel.setText("Desired room type");

        patientRoomTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRoomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        patientHospitalizationObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientHospitalizationObservationsLabel.setText("Observations");

        patientHospitalizationObservationsArea.setColumns(20);
        patientHospitalizationObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationObservationsArea.setRows(5);
        patientHospitalizationObservationsScrollPane.setViewportView(patientHospitalizationObservationsArea);

        patientRequestHospitalizationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRequestHospitalizationButton.setText("Create");
        patientRequestHospitalizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        patientCancelTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCancelTitleLabel.setText("Cancel appointment");

        patientCancelAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCancelAppointmentLabel.setText("ID appointment");

        patientCancelReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCancelReasonLabel.setText("Observations");

        patientCancelReasonArea.setColumns(20);
        patientCancelReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCancelReasonArea.setRows(5);
        patientCancelReasonScrollPane.setViewportView(patientCancelReasonArea);

        patientCancelAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCancelAppointmentButton.setText("Cancel");
        patientCancelAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        patientHospitalizationReasonArea.setColumns(20);
        patientHospitalizationReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientHospitalizationReasonArea.setRows(5);
        patientHospitalizationReasonScrollPane.setViewportView(patientHospitalizationReasonArea);

        patientAppointmentReasonArea.setColumns(20);
        patientAppointmentReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAppointmentReasonArea.setRows(5);
        patientAppointmentReasonScrollPane.setViewportView(patientAppointmentReasonArea);

        patientCancelAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCancelAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        patientDoctorOrSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientDoctorOrSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(patientRequestsPanel);
        patientRequestsPanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(patientBySpecialtyRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientByDoctorRadioButton))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(patientAppointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(patientAppointmentTimeLabel)
                                        .addComponent(patientAppointmentDateLabel)
                                        .addComponent(patientDoctorOrSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(patientAppointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(patientAppointmentReasonLabel))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(patientAppointmentTypeLabel))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(patientAppointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(patientAppointmentModeLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(patientAppointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(patientRequestAppointmentButton)))
                .addGap(69, 69, 69)
                .addComponent(patientFirstSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(patientRequestHospitalizationButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(patientHospitalizationReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientHospitalizationReasonScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(patientHospitalizationTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(patientHospitalizationDoctorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(patientHospitalizationObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(patientHospitalizationDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(patientHospitalizationObservationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(patientRoomTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(patientHospitalizationDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(patientHospitalizationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(patientRoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(patientSecondSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientCancelReasonScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(patientCancelTitleLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(patientCancelAppointmentButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(patientCancelAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientCancelAppointmentLabel)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(patientCancelReasonLabel)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientFirstSeparator)
            .addComponent(patientSecondSeparator)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(patientHospitalizationTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(patientHospitalizationReasonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientHospitalizationReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientHospitalizationDoctorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientHospitalizationDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientHospitalizationDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientHospitalizationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(patientRoomTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientRoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientHospitalizationObservationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientHospitalizationObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientRequestHospitalizationButton)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(patientAppointmentModeLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(patientBySpecialtyRadioButton)
                                    .addComponent(patientByDoctorRadioButton))
                                .addGap(18, 18, 18)
                                .addComponent(patientDoctorOrSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(patientAppointmentDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(patientAppointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(patientAppointmentTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(patientAppointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientAppointmentReasonLabel)
                                .addGap(24, 24, 24)
                                .addComponent(patientAppointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(patientCancelTitleLabel)
                                .addGap(39, 39, 39)
                                .addComponent(patientCancelAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(patientCancelAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(patientCancelReasonLabel)
                                .addGap(18, 18, 18)
                                .addComponent(patientCancelReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(patientCancelAppointmentButton)))
                        .addGap(18, 18, 18)
                        .addComponent(patientAppointmentTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientAppointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(patientRequestAppointmentButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        patientTabbedPane.addTab("Request/Cancel", patientRequestsPanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(patientRootPanel);
        patientRootPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patientTabbedPane)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(patientHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientTabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AppointmentController controller = new AppointmentController();
        Response response = controller.cancelAppointment(patientCancelAppointmentComboBox.getItemAt(patientCancelAppointmentComboBox.getSelectedIndex()));
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            refreshAppointmentsTable();
            loadPatientAppointmentCombo();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String firstname = patientFirstnameField.getText();
        String lastname = patientLastnameField.getText();
        boolean gender = patientGenderComboBox.getSelectedIndex() == 1;
        String birth = patientBirthdateField.getText();
        String address = patientAddressField.getText();
        String phone = patientPhoneField.getText();
        String email = patientEmailField.getText();
        String username = patientUsernameField.getText();
        String password = patientPasswordField.getText();
        String comPassword = patientPasswordConfirmationField.getText();
        UserController controller = new UserController();
        Response response = controller.updatePatient(String.valueOf(patientId), username, firstname, lastname, password,
                comPassword, email, birth, gender, phone, address);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            loadPatientData();
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        LoginView login = new LoginView();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AdminView admin = new AdminView(userId);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (patientByDoctorRadioButton.isSelected()) {
            patientByDoctorRadioButton.setSelected(false);
        }

        loadSpecialtiesCombo();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (patientBySpecialtyRadioButton.isSelected()) {
            patientBySpecialtyRadioButton.setSelected(false);
        }
        loadDoctorsCombo(patientDoctorOrSpecialtyComboBox);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String doctorId = null;
        String specialty = null;
        if (patientByDoctorRadioButton.isSelected()) {
            doctorId = patientDoctorOrSpecialtyComboBox.getItemAt(patientDoctorOrSpecialtyComboBox.getSelectedIndex());
        } else if (patientBySpecialtyRadioButton.isSelected()) {
            specialty = patientDoctorOrSpecialtyComboBox.getItemAt(patientDoctorOrSpecialtyComboBox.getSelectedIndex());
        }
        boolean appointmentType = patientAppointmentTypeComboBox.getSelectedIndex() == 2;
        AppointmentController controller = new AppointmentController();
        Response response = controller.requestAppointment(String.valueOf(patientId), doctorId, specialty,
                patientAppointmentDateField.getText(), patientAppointmentTimeField.getText(), patientAppointmentReasonArea.getText(), appointmentType);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            patientAppointmentDateField.setText("");
            patientAppointmentTimeField.setText("");
            patientAppointmentReasonArea.setText("");
            refreshAppointmentsTable();
            loadPatientAppointmentCombo();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        refreshAppointmentsTable();
        JOptionPane.showMessageDialog(this, "Citas cargadas.");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        HospitalizationController controller = new HospitalizationController();
        Response response = controller.requestHospitalization(String.valueOf(patientId), patientHospitalizationDoctorComboBox.getItemAt(patientHospitalizationDoctorComboBox.getSelectedIndex()), patientHospitalizationDateField.getText(),
                patientHospitalizationReasonArea.getText(), patientRoomTypeComboBox.getItemAt(patientRoomTypeComboBox.getSelectedIndex()), patientHospitalizationObservationsArea.getText());
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            patientHospitalizationDateField.setText("");
            patientHospitalizationReasonArea.setText("");
            patientHospitalizationObservationsArea.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loadPatientData() {
        Response response = new CatalogController().getUser(String.valueOf(patientId));
        if (!response.isSuccess()) {
            return;
        }
        JSONObject patient = new JSONObject(response.getData());
        patientFirstnameField.setText(patient.getString("firstname"));
        patientLastnameField.setText(patient.getString("lastname"));
        patientBirthdateField.setText(patient.getString("birthdate"));
        patientGenderComboBox.setSelectedIndex(patient.getBoolean("gender") ? 1 : 2);
        patientEmailField.setText(patient.getString("email"));
        patientPhoneField.setText(String.valueOf(patient.getLong("phone")));
        patientAddressField.setText(patient.getString("address"));
        patientUsernameField.setText(patient.getString("username"));
        patientPasswordField.setText("");
        patientPasswordConfirmationField.setText("");
    }

    private void loadRequestCombos() {
        loadDoctorsCombo(patientHospitalizationDoctorComboBox);
        patientRoomTypeComboBox.removeAllItems();
        for (RoomType roomType : RoomType.values()) {
            patientRoomTypeComboBox.addItem(roomType.name());
        }
        loadPatientAppointmentCombo();
    }

    private void loadDoctorsCombo(javax.swing.JComboBox<String> comboBox) {
        comboBox.removeAllItems();
        comboBox.addItem("Select one");
        Response response = new CatalogController().getDoctors();
        JSONArray doctors = new JSONArray(response.getData());
        for (int i = 0; i < doctors.length(); i++) {
            comboBox.addItem(String.valueOf(doctors.getJSONObject(i).getLong("id")));
        }
    }

    private void loadSpecialtiesCombo() {
        patientDoctorOrSpecialtyComboBox.removeAllItems();
        patientDoctorOrSpecialtyComboBox.addItem("Select one");
        Response response = new CatalogController().getSpecialties();
        JSONArray specialties = new JSONArray(response.getData());
        for (int i = 0; i < specialties.length(); i++) {
            patientDoctorOrSpecialtyComboBox.addItem(specialties.getJSONObject(i).getString("name"));
        }
    }

    private void loadPatientAppointmentCombo() {
        patientCancelAppointmentComboBox.removeAllItems();
        patientCancelAppointmentComboBox.addItem("Select one");
        Response response = new AppointmentController().getPatientAppointments(String.valueOf(patientId));
        JSONArray appointmentData = new JSONArray(response.getData());
        for (int i = 0; i < appointmentData.length(); i++) {
            JSONObject appointment = appointmentData.getJSONObject(i);
            if (!"COMPLETED".equals(appointment.getString("status"))) {
                patientCancelAppointmentComboBox.addItem(appointment.getString("id"));
            }
        }
    }

    private void refreshAppointmentsTable() {
        Response response = new AppointmentController().getPatientAppointments(String.valueOf(patientId));
        DefaultTableModel model = (DefaultTableModel) patientAppointmentsTable.getModel();
        model.setRowCount(0);
        JSONArray appointmentData = new JSONArray(response.getData());
        for (int i = 0; i < appointmentData.length(); i++) {
            JSONObject appointment = appointmentData.getJSONObject(i);
            model.addRow(new Object[]{appointment.getString("id"), appointment.getString("datetime"),
                appointment.getString("doctor"), appointment.getString("specialty"),
                appointment.getString("type"), appointment.getString("status")});
        }
    }

    public void onStoreChanged() {
        loadRequestCombos();
        refreshAppointmentsTable();
    }

    private void configureComponentNames() {
        patientCloseButton.setName("patientCloseButton");
        patientRequestAppointmentButton.setName("patientRequestAppointmentButton");
        patientRequestHospitalizationButton.setName("patientRequestHospitalizationButton");
        patientCancelAppointmentButton.setName("patientCancelAppointmentButton");
        patientRefreshAppointmentsButton.setName("patientRefreshAppointmentsButton");
        patientBackButton.setName("patientBackToAdminButton");
        patientLogoutButton.setName("patientLogoutButton");
        patientSaveProfileButton.setName("patientUpdateProfileButton");
        patientBySpecialtyRadioButton.setName("patientAppointmentBySpecialtyRadioButton");
        patientByDoctorRadioButton.setName("patientAppointmentByDoctorRadioButton");
        patientAppointmentTypeComboBox.setName("patientAppointmentTypeComboBox");
        patientHospitalizationDoctorComboBox.setName("patientHospitalizationDoctorComboBox");
        patientRoomTypeComboBox.setName("patientRoomTypeComboBox");
        patientCancelAppointmentComboBox.setName("patientCancelableAppointmentComboBox");
        patientDoctorOrSpecialtyComboBox.setName("patientAppointmentDoctorOrSpecialtyComboBox");
        patientGenderComboBox.setName("patientGenderComboBox");
        patientAppointmentsTable.setName("patientAppointmentsTable");
        patientHospitalizationObservationsArea.setName("patientHospitalizationObservationsArea");
        patientCancelReasonArea.setName("patientCancelReasonArea");
        patientHospitalizationReasonArea.setName("patientHospitalizationReasonArea");
        patientAppointmentReasonArea.setName("patientAppointmentReasonArea");
        patientFirstnameField.setName("patientFirstnameField");
        patientLastnameField.setName("patientLastnameField");
        patientBirthdateField.setName("patientBirthdateField");
        patientEmailField.setName("patientEmailField");
        patientPhoneField.setName("patientPhoneField");
        patientAddressField.setName("patientAddressField");
        patientPasswordField.setName("patientPasswordField");
        patientPasswordConfirmationField.setName("patientPasswordConfirmationField");
        patientUsernameField.setName("patientUsernameField");
        patientAppointmentDateField.setName("patientAppointmentDateField");
        patientAppointmentTimeField.setName("patientAppointmentTimeField");
        patientHospitalizationDateField.setName("patientHospitalizationDateField");
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton patientCloseButton;
    private javax.swing.JButton patientRequestAppointmentButton;
    private javax.swing.JButton patientRequestHospitalizationButton;
    private javax.swing.JButton patientCancelAppointmentButton;
    private javax.swing.JButton patientRefreshAppointmentsButton;
    private javax.swing.JButton patientBackButton;
    private javax.swing.JButton patientLogoutButton;
    private javax.swing.JButton patientSaveProfileButton;
    private javax.swing.JComboBox<String> patientAppointmentTypeComboBox;
    private javax.swing.JComboBox<String> patientHospitalizationDoctorComboBox;
    private javax.swing.JComboBox<String> patientRoomTypeComboBox;
    private javax.swing.JComboBox<String> patientCancelAppointmentComboBox;
    private javax.swing.JComboBox<String> patientDoctorOrSpecialtyComboBox;
    private javax.swing.JComboBox<String> patientGenderComboBox;
    private javax.swing.JLabel patientTitleLabel;
    private javax.swing.JLabel patientPasswordLabel;
    private javax.swing.JLabel patientPasswordConfirmationLabel;
    private javax.swing.JLabel patientUsernameLabel;
    private javax.swing.JLabel patientAppointmentModeLabel;
    private javax.swing.JLabel patientAppointmentDateLabel;
    private javax.swing.JLabel patientAppointmentTimeLabel;
    private javax.swing.JLabel patientAppointmentTypeLabel;
    private javax.swing.JLabel patientAppointmentReasonLabel;
    private javax.swing.JLabel patientHospitalizationTitleLabel;
    private javax.swing.JLabel patientHospitalizationReasonLabel;
    private javax.swing.JLabel patientFirstnameLabel;
    private javax.swing.JLabel patientHospitalizationDoctorLabel;
    private javax.swing.JLabel patientHospitalizationDateLabel;
    private javax.swing.JLabel patientRoomTypeLabel;
    private javax.swing.JLabel patientHospitalizationObservationsLabel;
    private javax.swing.JLabel patientCancelTitleLabel;
    private javax.swing.JLabel patientCancelAppointmentLabel;
    private javax.swing.JLabel patientCancelReasonLabel;
    private javax.swing.JLabel patientLastnameLabel;
    private javax.swing.JLabel patientBirthdateLabel;
    private javax.swing.JLabel patientGenderLabel;
    private javax.swing.JLabel patientEmailLabel;
    private javax.swing.JLabel patientPhoneLabel;
    private javax.swing.JLabel patientAddressLabel;
    private javax.swing.JPanel patientProfilePanel;
    private javax.swing.JPanel patientRequestsPanel;
    private javax.swing.JPanel patientHistoryPanel;
    private javax.swing.JRadioButton patientBySpecialtyRadioButton;
    private javax.swing.JRadioButton patientByDoctorRadioButton;
    private javax.swing.JScrollPane patientHospitalizationObservationsScrollPane;
    private javax.swing.JScrollPane patientCancelReasonScrollPane;
    private javax.swing.JScrollPane patientAppointmentsScrollPane;
    private javax.swing.JScrollPane patientHospitalizationReasonScrollPane;
    private javax.swing.JScrollPane patientAppointmentReasonScrollPane;
    private javax.swing.JSeparator patientFirstSeparator;
    private javax.swing.JSeparator patientSecondSeparator;
    private javax.swing.JTabbedPane patientTabbedPane;
    private javax.swing.JTable patientAppointmentsTable;
    private javax.swing.JTextArea patientHospitalizationObservationsArea;
    private javax.swing.JTextArea patientCancelReasonArea;
    private javax.swing.JTextArea patientHospitalizationReasonArea;
    private javax.swing.JTextArea patientAppointmentReasonArea;
    private javax.swing.JTextField patientFirstnameField;
    private javax.swing.JTextField patientPasswordConfirmationField;
    private javax.swing.JTextField patientUsernameField;
    private javax.swing.JTextField patientAppointmentDateField;
    private javax.swing.JTextField patientAppointmentTimeField;
    private javax.swing.JTextField patientHospitalizationDateField;
    private javax.swing.JTextField patientLastnameField;
    private javax.swing.JTextField patientBirthdateField;
    private javax.swing.JTextField patientEmailField;
    private javax.swing.JTextField patientPhoneField;
    private javax.swing.JTextField patientAddressField;
    private javax.swing.JTextField patientPasswordField;
    private packagee.PanelRound patientRootPanel;
    private packagee.PanelRound patientHeaderPanel;
    // End of variables declaration//GEN-END:variables
}
